#          |\__.__/|
#          )       (
#         =\       /=          .
#     |     )=====(       *          '
#    |     /       \             *        *
#   |     / dombili \       +                 '*
#  *      \        /
#  _/\_/\_/\_,  ,_/_/\_/\_/\_/\_/\_/\_/\_/\_/\_
#            )  )   This project is a part of the
#           (  (   “Byte-Sized JavaScript” videocasts.
#           )  )  Watch “Byte-Sized JavaScript” at: https://bytesized.tv/
#          (__(  MIT licensed — See LICENSE.md
#

language: node_js
node_js:
    - "8.1.3"
